version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_container
    environment:
      DATABASE_DIALECT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_NAME: todolist
      AUTO_LOAD_MODELS: true
      SYNCHRONIZE: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8080:80"
    depends_on:
      - nestjs
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
